
development:
  adapter: postgresql
  database: kitten_dev
  host: localhost
  username: appacademy


production:
  adapter: postgresql
  database: kitten_prod
  host: localhost
  username: appacademy
